version: "3"
services:
  web:
    build: server
    ports:
      - "4000:80"
  redis:
    image: redis
   
  php-redis-admin:
    image: faktiva/php-redis-admin
    container_name: pra
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - "8080:80"
    depends_on:
      - redis
